#!/bin/sh
OPTS="-x dict -x next"
rm -rf python3
cp -pR python python3

cd python3

2to3 $OPTS --write *.py > /dev/null 2>&1
rm -f *.bak *.pyc

cd tests
2to3 $OPTS --write *.py > /dev/null 2>&1
rm -f *.bak *.pyc
rm -rf testdata/* testgeodata/*
cd ..

cd phonenumbers
2to3 $OPTS --write *.py > /dev/null 2>&1
# reinstate util.py as it is version-aware
cp ../../python/phonenumbers/util.py .
2to3 $OPTS --write --doctests_only *.py > /dev/null 2>&1
rm -f *.bak *,cover *.pyc
rm -rf data/* geodata/__init__.py*
cd geodata
2to3 $OPTS --write locale.py > /dev/null 2>&1
rm -f *.bak
cd ..
cd ..

# Alter this line to use the local invocation command for Python 3k
sed 's/^PYTHON=python$/PYTHON=python3/' makefile > makefile.tmp$$
mv makefile.tmp$$ makefile

make alldata