#!/bin/sh
rm -rf python3
cp -pR python python3

cd python3

2to3 --write *.py > /dev/null 2>&1
rm -f *.bak *.pyc

cd tests
2to3 --write *.py > /dev/null 2>&1
rm -f *.bak *.pyc
rm -rf testdata/* testgeodata/*
cd ..

cd phonenumbers
2to3 --write *.py > /dev/null 2>&1
2to3 --write --doctests_only *.py > /dev/null 2>&1
rm -f *.bak *,cover *.pyc
rm -f data/* geodata/__init__.py*
cd geodata
2to3 --write locale.py > /dev/null 2>&1
rm -f *.bak
cd ..
cd ..

# Alter this line to use the local invocation command for Python 3k
sed 's/^PYTHON=python$/PYTHON=python3/' makefile > makefile.tmp$$
mv makefile.tmp$$ makefile
sed 's/^PACKAGE=phonenumbers$/PACKAGE=phonenumbers3k/' makefile > makefile.tmp$$
mv makefile.tmp$$ makefile
sed 's/python3 = false/python3 = true/' DumpLocale.java > DumpLocale.java.tmp$$
mv DumpLocale.java.tmp$$ DumpLocale.java

make geodata metadata locale