class AsYouTypeFormatter:
    def __init__(self, region_code: str) -> None: ...
    def clear(self) -> None: ...
    def input_digit(self, next_char: "str", remember_position: bool = ...) -> str: ...
    def get_remembered_position(self) -> int: ...
