from typing import Optional

from .phonenumber import PhoneNumber

def name_for_valid_number(numobj: PhoneNumber, lang: str, script: Optional[str] = ..., region: Optional[str] = ...): ...
def name_for_number(numobj: PhoneNumber, lang: str, script: Optional[str] = ..., region: Optional[str] = ...): ...
def safe_display_name(numobj: PhoneNumber, lang: str, script: Optional[str] = ..., region: Optional[str] = ...): ...
