from typing import Optional

from .phonenumber import PhoneNumber

def country_name_for_number(numobj: PhoneNumber, lang: str, script: Optional[str] = ..., region: Optional[str] = ...): ...
def description_for_valid_number(numobj: PhoneNumber, lang: str, script: Optional[str] = ..., region: Optional[str] = ...): ...
def description_for_number(numobj: PhoneNumber, lang: str, script: Optional[str] = ..., region: Optional[str] = ...): ...
